version: '3.8'
services:
 emongo:
  image: mongo:4
  container_name: emongo
  ports:
   - "27017:27017"
  environment:
    - MONGO_INIDB_DATABASE=epoc

 emartdb:
  image: mysql:8.0
  container_name: emartdb
  ports:
   - "3306:3306"
  environment:
   - MYSQL_ROOT_PASSWORD=emartdbpass
   - MYSQL_DATABASE=books

 nginx:
  image: nginx:latest
  restart: always
  container_name: nginx
  ports:
   - "80:80"
  volumes:
   - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"

 api:
  build:
   context: ./nodeapi
  ports:
     - "5000:5000"
  container_name: api
  depends_on:
    - nginx
    - emongo


 webapi:
  restart: always
  build:
   context: ./javaapi
  ports:
    - "9000:9000"
  container_name: webapi
  depends_on:
    - emartdb

 client:
  build:
   context: ./client
  container_name: client
  ports:
   - "4200:4200"
  depends_on:
   - api
